name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          base: metadata
          config_display: columns
          config_timezone: America/Los_Angeles
          
          plugin_achievements: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_habits: yes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
